---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
services:
  - docker
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-6-x64
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-7-x64
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false
